tasks:
  - name: Setup and Build
    before: |
      # Download and Install Java 17.0.6-tem
      yes Y | sdk install java 17.0.6-tem

    init: |
      # Run
      mvn hpi:run

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency